scrollbar css changed
codeforcauseorg/codeforcause.org pull request #120
Opened 2020-10-04 22:59 UTC by ArunTeltia

customized the scrollbar as per #119 issue

2020-10-04 23:02 UTC, Abhishek-kumar09 commented on src/App.css
> +::-webkit-scrollbar-track {
Just realizied that you had made a seperate css file for this, but can't we do it with makeStyles?

2020-10-04 23:04 UTC, ArunTeltia commented on src/App.css
> +::-webkit-scrollbar-track {
Actually we cant apply psuedo selector css inline 
Have a look at this 
https://stackoverflow.com/questions/47345981/customize-webkit-scrollbar-inline-with-react

2020-10-04 23:07 UTC, Abhishek-kumar09 commented
I cant see your changes with build preview, Is it same from your side?
![Screenshot from 2020-10-05 04-34-08](https://user-images.githubusercontent.com/48255244/95029232-60a95980-06c4-11eb-8f0a-df221d50bd93.png)

2020-10-04 23:09 UTC, Abhishek-kumar09 commented on src/App.css
> +
please add a newline at the end of file.

2020-10-04 23:12 UTC, ArunTeltia commented on src/App.css
> +
okay , I will 
but for the above query for me its working in whole website

2020-10-04 23:15 UTC, ArunTeltia commented on src/App.css
> +
can you tell me more about newline please

2020-10-04 23:17 UTC, Abhishek-kumar09 commented
> but for the above query for me its working in whole website

Okay, now I got it...Webkit is only working with chrome, you have to additionally add `-moz-` support to make the webpage same in both browser. Currently you can't see your changes with mozilla.

2020-10-04 23:20 UTC, ArunTeltia commented
okay so i will add more classes for other browser support

2020-10-04 23:22 UTC, Abhishek-kumar09 commented on src/App.css
> +
You have to end every file with a blank line according to POSIX standards. In this file you could see that the line written with your code is the last line, but that should not be the case. You should add a newline blank line.

2020-10-04 23:25 UTC, ArunTeltia commented on src/App.css
> +
okay wait

2020-10-05 00:08 UTC, ArunTeltia commented
check this view for mozzilla @Abhishek-kumar09 
check this stack overflow thread
https://stackoverflow.com/questions/56975071/how-to-make-firefox-scrollbar-thinner-than-thin
the scrollbar issue in firefox is relatively new
![moz-view](https://user-images.githubusercontent.com/43555219/95030211-c220f680-06cb-11eb-8339-193dd603c10e.JPG)
now i also checked the ways to make the scrollbar thin and curved and i got to this reddit post 
https://www.reddit.com/r/firefox/comments/7f6kc4/floating_scrollbar_finally_possible_in_firefox_57/

2020-10-06 18:14 UTC, Abhishek-kumar09 commented
Hey @ArunTeltia, can we make a carasouel out of this horizontal scrolling and leave the scroll color as it is?

2020-10-06 22:16 UTC, ArunTeltia commented
yes but it would be okay for laptop users to scroll sidewise what about the pc users they need some scrollbar to scroll for reading testimonials

2020-10-07 14:15 UTC, Abhishek-kumar09 commented
@ArunTeltia, some changes: 
- Replace the previous scroll bars 
- Delete App.css
- About testimonial section: We want some automatic scrolling on testimonial section, the cards should move horizontally automatically.

2020-10-07 14:20 UTC, ArunTeltia commented
remove scroll bar in testimonials and make them movable ?
okay i will do that

2020-10-10 09:16 UTC, KeenWarrior commented
@ArunTeltia Any update

2020-10-10 12:33 UTC, ArunTeltia commented
Working on it sir @KeenWarrior

2020-10-10 15:10 UTC, ArunTeltia commented
@Abhishek-kumar09 , i know how to make this infinitely moving by writing advance css for example adding animation and keyframes but i dont know if that is being supported by react inline style , can i use a library for implementing this feature or i can simply add a css file ?
```
animation: animate 60s linear infinite;
```
this is the line of css i need to write for the smooth transitional effect 
Please check this out

2020-10-10 15:31 UTC, Abhishek-kumar09 commented
OK, you could write it with creating a new css file or use makeStyles(), its your choice we are happy with both.

2020-10-10 17:58 UTC, ArunTeltia commented
![Code-for-Cause-Google-Chrome-202](https://user-images.githubusercontent.com/43555219/95661849-3a663c80-0b50-11eb-9193-1f9d80d238c9.gif)
It is going to and fro first go to last then go bact to first

2020-10-10 18:39 UTC, Abhishek-kumar09 commented
Its looking great now, Please commit those changes here.

2020-10-10 18:51 UTC, ArunTeltia commented
can you help me with how to get the commits from the upstream 
I dont know how to do that 
Or i can create a new branch and add add a new pr ?

2020-10-10 18:54 UTC, Abhishek-kumar09 commented
do:
- git remote add upstream <url>
- git fetch upstream
- git rebase upstream/development
-git push -f

2020-10-10 19:12 UTC, Abhishek-kumar09 approved these changes

2020-10-10 19:18 UTC, ArunTeltia commented
I just check I accidently removed the comments do i have to add those ?

2020-10-10 19:23 UTC, Abhishek-kumar09 commented
Its safe if you could restore those.

2020-10-11 19:14 UTC, Abhishek-kumar09 commented
@ArunTeltia Please make it uni-directional, infinite. Sorry I gave you wrong info before, we have update to keep it unidirectional and infinite movement.

2020-10-11 21:37 UTC, ArunTeltia commented
u mean it must be an infinite loop? 
Okay give me time i will do that

2020-10-11 23:25 UTC, ArunTeltia commented
can you help me with this i tried but i am not able to make it look like circular 
My deduction:
I will need a js library for implementing this 
2nd 
I will need to duplicate the cards such that i can make them appear side by side like a circular linked list and than i can try animation that 
For now I can make the list disappear as it go left and after it disappear it will start to reappear from the  right 
but there will be a gap between those 
Please help me
PS: I dont like libraries i like to right pure css so it would be great if you recommend me a library to implement this feature

2020-10-12 00:14 UTC, ArunTeltia commented
Okay so what i did is add 3 starting cards at the end of the cardlist in the grid so that there is no gap between each other 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/43555219/95694119-e93c7280-0c4d-11eb-99ab-4478313d75ba.gif)

2020-10-12 00:16 UTC, ArunTeltia commented
Please check @KeenWarrior @Abhishek-kumar09

2020-10-12 08:34 UTC, Abhishek-kumar09 requested changes

2020-10-12 08:34 UTC, Abhishek-kumar09 commented on src/views/pages/common/Recommendations.js
> +                      <Typography
> Okay so what i did is add 3 starting cards at the end of the cardlist in the grid so that there is no gap between each other

Please remove this, as no one is gonna starr at testimonial for so long, and afterall we are still getting some motion discontinuity after those 3 added card. I think., else is great :1st_place_medal:

2020-10-12 08:38 UTC, ArunTeltia commented on src/views/pages/common/Recommendations.js
> +                      <Typography
Okay got it let me check that

2020-10-12 08:48 UTC, ArunTeltia commented on src/views/pages/common/Recommendations.js
> +                      <Typography
Why I have to remove these lines These are essential piece of code and will break the component totally 
Can you please recheck @Abhishek-kumar09

2020-10-12 10:50 UTC, Abhishek-kumar09 commented on src/views/pages/common/Recommendations.js
> +                      <Typography
Oh Sorry my mistake, you have to remove the code for 3 extra cards that you had added.

2020-10-12 17:03 UTC, ArunTeltia commented on src/views/pages/common/Recommendations.js
> +                      <Typography
oh okay

2020-10-12 18:26 UTC, ArunTeltia commented
Okay done @Abhishek-kumar09 you can check 
Please also allot one more issue to me :D

2020-10-12 18:29 UTC, Abhishek-kumar09 approved these changes

2020-10-12 18:36 UTC, Abhishek-kumar09 commented
> Please also allot one more issue to me :D

Great you are enthuastic about it!
Wanna try:  https://github.com/codeforcauseorg/codeforcause.org/issues/95 its bit complicated and some part of it is done, you could always take help from that. But ofcourse your personal ground level idea is more welcome, because in earlier approach there were some problems that's why it could only solve the issue partially.

2020-10-12 18:57 UTC, ArunTeltia commented
Great will start work right away via reading previous logs

2020-10-18 14:38 UTC, merged