Removing all the console errors from the development environment (#92).
codeforcauseorg/codeforcause.org pull request #197
Opened 2021-01-13 09:56 UTC by Itsaadarsh

Removed all the console error's as mentioned in **(#92)**, but as far as warnings are concerned there were 3 warnings that showed up in the development environment and they could only be cleared by upgrading packages but I didn't do that as I did not want to break any existing piece of code and on the flip side they only pop up on dev env and not on production env.

There is this workaround where I can write `console.warn() => {}` on root component which basically does not through any console warning what so ever but this practice is not good for the long run so I just let to be like that.

![image](https://user-images.githubusercontent.com/54549066/104436037-1e40c400-55b3-11eb-9fdf-9f86d18c7a00.png)

2021-01-13 10:08 UTC, Abhishek-kumar09 commented
Thanks for your PR, one problem:
This is broken: 
![image](https://user-images.githubusercontent.com/48255244/104437859-50532580-55b5-11eb-847b-c1ad795bea5a.png)

2021-01-13 10:34 UTC, Itsaadarsh commented
Fixed CSS bug in Courses.js (#92) @Abhishek-kumar09 

![image](https://user-images.githubusercontent.com/54549066/104440942-02402100-55b9-11eb-860a-024051a2c13b.png)

2021-01-15 09:38 UTC, Abhishek-kumar09 commented
Please resolve conflicts.

2021-01-16 08:35 UTC, Abhishek-kumar09 commented
package-lock.json has still conflicts.

2021-01-16 08:38 UTC, Abhishek-kumar09 commented
You can rebase your branch on the development branch, as the changes are not synchronised. You previous merged PR has all the changes for package.json and some other files, still in the diff we are getting those files.

Rebasing your branch over latest development will solve this problem.

2021-01-16 10:20 UTC, Itsaadarsh commented
Done mate @Abhishek-kumar09 , thanks for the guidance. Anything else?

2021-01-16 11:20 UTC, Abhishek-kumar09 approved these changes
Thanks for your PR. Everything is looking good!

2021-01-29 12:32 UTC, Abhishek-kumar09 requested changes
Thanks for your PR @Itsaadarsh, Really sorry we could not catchup due to some other things on our pipeline and you had to wait.

Some minor changes for now.

2021-01-29 12:32 UTC, Abhishek-kumar09 commented on src/views/pages/HomeView/CTA.js
> +                <Grid item xs={12} sm={12}>
same here, because containers are used to contain different grid items and thus can't be used as items alone.
remove `xs` and `sm` from containers.

2021-01-29 12:32 UTC, Abhishek-kumar09 commented on src/views/pages/HomeView/CTA.js
> +                <Grid item xs={12} sm={12}>
@Itsaadarsh 
Please change it to:
` <Grid item xs={12} sm={12}>` => `<Grid container>`

2021-01-29 12:32 UTC, Abhishek-kumar09 commented on src/views/pages/HomeView/CTA.js
> +                <Grid item xs={12} sm={12}>
Same.

2021-01-29 12:32 UTC, Abhishek-kumar09 commented on src/views/pages/HomeView/Courses.js
> +              }}
Try to remove  `display` and `alignItem` props and also `style` from here and check if there is change in behaviour.
Because display and alignItems are not the the properties of `GridList` and hence it would not have done any change due to these props I guess, so removing them may not change anything, but you can confirm it.

2021-01-29 12:41 UTC, Abhishek-kumar09 commented
One more thing, before you get into trouble of github rebase and anything like that.
I have changed your package.json file and it may create some conflicts, either you could rebase or force push the branch for now.
Since rebasing would cause a lot of problem to you since you have 6 commits history, therefore, you could force push your branch with ease after doing these changes, and then change the current package.json file to the the package.json file from the codeforcause.org repo.

Actually, I was about to merge this PR, thus changed your package.json file, but then found some minor issues.

2021-02-19 07:42 UTC, Abhishek-kumar09 commented
Thanks @Itsaadarsh for your PR and your hardwork.

2021-02-19 07:42 UTC, merged

2021-02-19 08:11 UTC, Itsaadarsh commented
@Abhishek-kumar09 My pleasure, let me know if something else is needed I'd love to contribute more.