Hire with Us Hero Component
codeforcauseorg/codeforcause.org pull request #206
Opened 2021-02-01 08:16 UTC by mdPial

This PR is for the issue #200 .

- [x] Things are made/changed
* `Route` for the page
* image in `public/static/images/hire-with-us/hero.png`
* `Hero` component **HeroWithBackgroundImage**
* In  `src/views/pages/HireWithUsView/Hero.js`
      * index page
      * Hero component

2021-02-01 12:32 UTC, Abhishek-kumar09 requested changes
Cool, 
Some minors to change:
- Lesson the padding of the content on smaller screens.
- make the button opaque on hover, opacity should be 1. We will likely change the color of the button on hover too, but lets try it before something else.

2021-02-01 14:57 UTC, mdPial commented
@Abhishek-kumar09 Sorry, I didn't understand. What you meant by the `Lesson` word

2021-02-01 15:01 UTC, Abhishek-kumar09 commented
Oh Sorry, It is lessen meaning change padding to be little less than the usual desktop paddings when switched to smaller screens.

2021-02-01 16:58 UTC, mdPial commented
Oh. No problem. I actually guessed that after thinking then I thought any keyword might be for professional works 🤣

2021-02-02 14:17 UTC, mdPial commented
@Abhishek-kumar09 I got confused about reducing padding because I haven't used any 😅️. Though I have done some changes based on the screen. Please let me know if I made any mistakes. And please give me some guideline on asking questions maybe I am not asking questions properly because of my shyness.

2021-02-03 03:27 UTC, mdPial commented on src/components/Hero/HeroWithBackgroundImage.js
> +      marginLeft: '120px'
[theme.breakpoints.down('sm')]: {
      margin: theme.spacing(3)
}
like this?

2021-02-03 08:00 UTC, Abhishek-kumar09 commented on src/components/Hero/HeroWithBackgroundImage.js
> +      marginLeft: '120px'
`[theme.breakpoints.down('sm')]: margin: theme.spacing(3) `
like this

2021-02-03 09:09 UTC, mdPial commented on src/components/Hero/HeroWithBackgroundImage.js
> +      marginLeft: '120px'
Oh, Okay, github formatted my code into one line 😅️. I just wanted to ask. Do I have to give the margin all side like that or only in the left side.

2021-02-03 09:18 UTC, mdPial commented
@Abhishek-kumar09 I have made changes.

2021-02-03 09:26 UTC, Abhishek-kumar09 commented
Ya, its looking really good. I will review the changes after some time, if it is ok.

2021-02-03 09:33 UTC, mdPial commented
> Ya, its looking really good. I will review the changes after some time, if it is ok.

Take your time. I have no problem😃️

2021-02-06 08:01 UTC, Abhishek-kumar09 approved these changes

2021-02-06 08:02 UTC, Abhishek-kumar09 commented
Thanks @mdPial for your wonderful contribution.

2021-02-06 08:02 UTC, Abhishek-kumar09 commented
merging once ci pass

2021-02-06 08:09 UTC, merged

2021-02-06 14:36 UTC, mdPial commented
> Thanks @mdPial for your wonderful contribution.

Welcome. Feeling great, at last merged 😁️

2021-02-06 15:40 UTC, Abhishek-kumar09 commented
You can also checkout click-short or certificate-generator-react they are also new projects that we are building now, but due some time constraints it is slow.

2021-02-06 16:00 UTC, mdPial commented
> You can also checkout click-short or certificate-generator-react they are also new projects that we are building now, but due some time constraints it is slow or could also try to solve some new issues in this repo.

Thank you for the suggestion 😀️. I was looking to contribute as much as I can possible. Because I had gained the courage to contribute after watching videos of **codeforcause** 😁️. Thank you for guideline 😃️ along the way I never used Material UI before.

2021-02-06 17:17 UTC, Abhishek-kumar09 commented
Thanks for kind words.