Added New Component In HireWithUs
codeforcauseorg/codeforcause.org pull request #212
Opened 2021-02-06 17:12 UTC by atharmohammad

2021-02-06 17:17 UTC, atharmohammad commented
@Abhishek-kumar09  Can you please tell me Why checks are Failing,Thanks

2021-02-06 17:27 UTC, Abhishek-kumar09 commented on src/views/pages/HireWithUsView/Developer/DevBox/index.js
> +            <img src={img} className={classes.Gold_Ribbon}/>
`img` should have a alt prop.

2021-02-06 17:59 UTC, atharmohammad commented
@Abhishek-kumar09  Thanks man, Look at changes

2021-02-06 18:57 UTC, Abhishek-kumar09 commented on public/index.html
> +<link href="https://fonts.googleapis.com/css2?family=Roboto:ital@1&display=swap" rel="stylesheet">
Why these changes?

2021-02-06 18:57 UTC, Abhishek-kumar09 commented on src/views/pages/HireWithUsView/Developer/Developer.js
> +              Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a g
Actually you can use Typography, which is already defined in `material-ui`. https://github.com/codeforcauseorg/codeforcause.org/blob/development/src/theme/typography.js

You have a look on the documentation here: https://material-ui.com/api/typography/

2021-02-07 05:25 UTC, atharmohammad commented on public/index.html
> +<link href="https://fonts.googleapis.com/css2?family=Roboto:ital@1&display=swap" rel="stylesheet">
I added a google font link ,removed it in this commit

2021-02-07 05:25 UTC, atharmohammad commented on src/views/pages/HireWithUsView/Developer/Developer.js
> +              Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a g
Ok , added it in the component , review it

2021-02-07 06:06 UTC, Abhishek-kumar09 requested changes
We use material-ui for our styling and use typography where we have to show some text so that the code is more consistent and less written. Changes are good but minor changes for now.

2021-02-07 06:06 UTC, Abhishek-kumar09 commented on src/views/pages/HireWithUsView/Developer/DevBox/index.js
> +          <strong><p>Problems Solved</p></strong>
Please use Typogaphy here.

2021-02-07 06:06 UTC, Abhishek-kumar09 commented on src/views/pages/HireWithUsView/Developer/Developer.js
> +           <span className={classes.heading2}>The Fine Developer</span></p>
PLease use typography here.

2021-02-07 06:23 UTC, atharmohammad commented on src/views/pages/HireWithUsView/Developer/Developer.js
> +           <span className={classes.heading2}>The Fine Developer</span></p>
Added Tell me if more Changes required

2021-02-07 06:23 UTC, atharmohammad commented on src/views/pages/HireWithUsView/Developer/DevBox/index.js
> +          <strong><p>Problems Solved</p></strong>
added

2021-02-07 10:51 UTC, Abhishek-kumar09 commented
I can't see the vertical transparent glass in my web : 
![image](https://user-images.githubusercontent.com/48255244/107144326-7f647900-6960-11eb-90b2-c3d63c9f89e3.png)
But is seen in your screenshot: https://user-images.githubusercontent.com/56029409/107119614-da3d9800-68ae-11eb-8a76-51d3e6105d10.PNG

2021-02-07 12:08 UTC, Abhishek-kumar09 commented
https://deploy-preview-212--eloquent-turing-542749.netlify.app/hirewithus
It is still not visible, If you have added and it is not visible then the problem may be with `zIndex` probably.

2021-02-07 12:08 UTC, atharmohammad commented
> I can't see the vertical transparent glass in the extreme right in my web :
Even though it is visible in my web browser , may be its because of zoom difference I commit some changes , try it now ...try 100% zoom of browser window

2021-02-07 12:10 UTC, atharmohammad commented
@Abhishek-kumar09  SideBar css is used for that ...I have already given it larger z-index

2021-02-07 12:12 UTC, atharmohammad commented
> https://deploy-preview-212--eloquent-turing-542749.netlify.app/hirewithus
> It is still not visible, If you have added and it is not visible then the problem may be with `zIndex` probably.

I am looking into it ... Do my changes appears here as i commit so can see if it appears or not

2021-02-07 12:31 UTC, atharmohammad commented
@Abhishek-kumar09  Ok,So opactiy was the problem Which was supported in my browser by 80% so I have Now changed it to 0.8 Now You can see the side bar,Thanks

2021-02-07 15:34 UTC, Abhishek-kumar09 commented
Cool, these changes are good forward leap. Could you use material-ui styles it's same as the current css all the properties work same there too, just we have everything in one file so that it is more organized. There are plenty of files that uses material-ui styles you can definately look into that how it is done. Meanwhile you will get a chance to learn about it too.

2021-02-07 17:08 UTC, atharmohammad commented
@Abhishek-kumar09 yes, I saw that  in the code , will convert css as per the  application structure 👍

2021-02-07 18:13 UTC, atharmohammad commented
@Abhishek-kumar09  Done, Review Changes,Thanks 👍

2021-02-07 18:25 UTC, Abhishek-kumar09 commented
Looks good, thanks for the PR @atharmohammad.

2021-02-07 18:25 UTC, merged