Console Errors for Course Page fixed
codeforcauseorg/codeforcause.org pull request #233
Opened 2021-02-22 20:35 UTC by PrashubhAtri

Fixes #232

2021-02-23 18:51 UTC, Abhishek-kumar09 requested changes
Looks really good, some minors for now.

2021-02-23 18:51 UTC, Abhishek-kumar09 commented on src/components/popups/autoPopupDialog.js
> +            autoComplete=""
You can remove this field if it was not doing anything.

2021-02-23 18:51 UTC, Abhishek-kumar09 commented on src/components/popups/autoPopupDialog.js
> +                autoComplete=""
same

2021-02-25 17:17 UTC, PrashubhAtri commented on src/components/popups/autoPopupDialog.js
> +                autoComplete=""
Done :)

2021-02-25 17:20 UTC, PrashubhAtri reviewed
Completed and submitted again

2021-02-26 08:13 UTC, Abhishek-kumar09 commented
Something not working correcting: The items are shrinked.
![image](https://user-images.githubusercontent.com/48255244/109273698-8af8e080-7838-11eb-9a20-f59eacb89036.png)
![image](https://user-images.githubusercontent.com/48255244/109273733-98ae6600-7838-11eb-8bcd-0f0033b75052.png)

2021-02-27 19:24 UTC, PrashubhAtri commented
> Something not working correctly: The items are shrinked.
> ![image](https://user-images.githubusercontent.com/48255244/109273698-8af8e080-7838-11eb-9a20-f59eacb89036.png)
> ![image](https://user-images.githubusercontent.com/48255244/109273733-98ae6600-7838-11eb-8bcd-0f0033b75052.png)

While resloving issues regarding the properties being used on Grid, I had to add "container" to it which has by default a display=flex which is causing the fault, can you please suggest a fix as I am not so familiar with material UI and there is no specific solution on the net.

2021-02-27 19:32 UTC, PrashubhAtri commented
Please Check and review

2021-03-03 09:01 UTC, merged

2021-03-03 09:01 UTC, Abhishek-kumar09 commented
Thanks for your contribution @PrashubhAtri The changes are looking fine to me.