Css fix
codeforcauseorg/codeforcause.org pull request #57
Opened 2020-08-09 16:48 UTC by Abhishek-kumar09

Closes #11

2020-08-09 16:54 UTC, Abhishek-kumar09 commented
I have added montserrat to every Typography, I didn't found any other good way...There are no css files dedicated to these.
Also, There are lots of extra(bulky) code written which is not handy or may be difficult to understand  for new contributors, I think!

2020-08-12 21:11 UTC, GangaChatrvedi commented
@Abhishek-kumar09 Take a look at [this](https://material-ui.com/customization/typography/).

2020-08-13 10:34 UTC, Abhishek-kumar09 commented
> @Abhishek-kumar09 Take a look at this.

Thanks, great help.

2020-09-21 09:44 UTC, KeenWarrior requested changes

2020-09-21 09:44 UTC, KeenWarrior commented on src/theme/typography.js
> +    '"Montserrat"',
just keep Montserrat and remove others

2020-09-21 09:44 UTC, KeenWarrior commented on src/layouts/MainLayout/TopBar/index.js
> -          <Box ml={2} flexGrow={0.05} />
revert this

2020-09-21 09:44 UTC, KeenWarrior commented on src/components/HeaderItems.js
> +    padding: ' 19px 10px',
revert this

2020-09-21 09:45 UTC, KeenWarrior commented
@Abhishek-kumar09 Please rebase and make the above changes. 

Then We can continue to find where the fonts still face issues in the sandbox.

2020-09-21 12:46 UTC, Abhishek-kumar09 commented on src/theme/typography.js
> +    '"Montserrat"',
If the Monteserrat font is not fetched somehow, than It will show the very basic Aerial(I guess). So atleast two fonts are required I think. 
Else it's your choice. I would remove the rest.

2020-09-21 13:16 UTC, Abhishek-kumar09 commented on src/theme/typography.js
> +    '"Montserrat"',
Done

2020-09-21 16:05 UTC, Abhishek-kumar09 commented on src/layouts/MainLayout/TopBar/index.js
> -          <Box ml={2} flexGrow={0.05} />
Done

2020-09-21 16:05 UTC, Abhishek-kumar09 commented on src/components/HeaderItems.js
> +    padding: ' 19px 10px',
Done

2020-09-21 17:02 UTC, merged