Dynamically change the remaining number of characters required.
codeforcauseorg/codeforcause.org pull request #88
Opened 2020-09-23 16:33 UTC by aymenhamada

Dynamically change the remaining number of characters required.

Issue : #81

2020-09-23 17:21 UTC, Abhishek-kumar09 requested changes
Nicely Done.
Run `npm run format` before pushing your next commit.

2020-09-23 17:21 UTC, Abhishek-kumar09 commented on src/views/pages/ApplicationsView/ApplicationSteps.js
> +          `Text too short. Put in atleast 150 chars. ${formData.q1 && formData.q1.length ? "Remaining " + (150 - formData.q1.length) + `${formData.q1.length < 149 ?  " characters" : " character"}`: "
You should only display:
Text too short. Put in `x` characters more.

2020-09-23 17:27 UTC, aymenhamada commented on src/views/pages/ApplicationsView/ApplicationSteps.js
> +          `Text too short. Put in atleast 150 chars. ${formData.q1 && formData.q1.length ? "Remaining " + (150 - formData.q1.length) + `${formData.q1.length < 149 ?  " characters" : " character"}`: "
Sure i'll fix that.

2020-09-23 21:03 UTC, aymenhamada commented
Added a variable containing the minimum number of characters required
`  const MIN_CHAR = 150;`

Also added a function to calculate the real length of a string (Removing white space, so user can't submit 150 wihte space)
`const countChar = string => {
    return string.replace(/\s/g, '').length;
 };`

2020-09-24 08:39 UTC, Abhishek-kumar09 approved these changes

2020-09-24 09:08 UTC, merged

2020-09-24 09:09 UTC, KeenWarrior commented
Nice work @aymenhamada  🥳